/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package View;

import DAO.EnderecosDao;
import Model.Enderecos;
import java.awt.Toolkit;
import java.net.URL;
import javax.swing.JOptionPane;
import static javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author mateus
 */
public class EnderecosTela extends javax.swing.JDialog {

    /**
     * Creates new form NewJDialog
     * @param parent
     * @param modal
     */
    public EnderecosTela(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setSize(700, 600);// Define resolução tela
        setDefaultCloseOperation(DO_NOTHING_ON_CLOSE); //impede de fechar com X
        setLocationRelativeTo(null); //Define a posição como centro da tela
        setTitle("Cadastrar Endereço");// Titulo da tela
        setResizable(false); //Impede de redimensionar tela
        jTFId.setEnabled(false); //Desabilita campo Id
        jBDeletar.setEnabled(false);//Desabilita campo deletar
        jBAlterar.setEnabled(false); //Desabilita campo alterar
        jBSelecionar.setEnabled(false); //Desabilita campo selecionar
        URL caminhoImagem = this.getClass().getClassLoader().getResource("./images/project/icon-petshop-100.png"); //localiza o icone
        setIconImage(Toolkit.getDefaultToolkit().getImage(caminhoImagem));//define o icone
        preencherTabela();//Preenche tabela com os dados retornados do banco
    }

    public void preencherTabela() {
        DefaultTableModel modelo = (DefaultTableModel) jTable2.getModel();
        modelo.setNumRows(0);
        EnderecosDao eDAO = new EnderecosDao();
        for (Enderecos end : eDAO.ler()) {
            modelo.addRow(new Object[]{
                end.getId(),
                end.getLogradouro(),
                end.getNumero(),
                end.getBairro(),
                end.getCidade(),
                end.getEstado(),
                end.getCep(),
                end.getComplemento()
            });
        }
    }

    public void preencherTabelaPesquisar(String desc) {
        DefaultTableModel modelo = (DefaultTableModel) jTable2.getModel();
        modelo.setNumRows(0);
        EnderecosDao eDAO = new EnderecosDao();
        for (Enderecos end : eDAO.ler2(desc)) {
            modelo.addRow(new Object[]{
                end.getId(),
                end.getLogradouro(),
                end.getNumero(),
                end.getBairro(),
                end.getCidade(),
                end.getEstado(),
                end.getCep(),
                end.getComplemento()
            });
        }
    }

private int valorId;

    public int getValorId() {
        return valorId;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTFLogradouro = new javax.swing.JTextField();
        jTFBairro = new javax.swing.JTextField();
        jTFEstado = new javax.swing.JTextField();
        jTFCidade = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jBGravar = new javax.swing.JButton();
        jBSair = new javax.swing.JButton();
        jTFNumero = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jBAlterar = new javax.swing.JButton();
        jBDeletar = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jTFId = new javax.swing.JTextField();
        jBLimpar = new javax.swing.JButton();
        jBPesquisar = new javax.swing.JButton();
        jTFPesquisar = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTFComplemento = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jBSelecionar = new javax.swing.JButton();
        jTFCep = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        jTFLogradouro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFLogradouroActionPerformed(evt);
            }
        });
        getContentPane().add(jTFLogradouro);
        jTFLogradouro.setBounds(30, 40, 210, 22);
        getContentPane().add(jTFBairro);
        jTFBairro.setBounds(30, 100, 140, 22);
        getContentPane().add(jTFEstado);
        jTFEstado.setBounds(310, 100, 40, 22);
        getContentPane().add(jTFCidade);
        jTFCidade.setBounds(180, 100, 120, 22);

        jLabel1.setText("Logradouro");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(30, 20, 140, 16);

        jLabel2.setText("CEP");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(30, 140, 140, 16);

        jLabel3.setText("Bairro");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(30, 80, 130, 16);

        jLabel4.setText("Estado");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(310, 80, 40, 16);

        jLabel5.setText("Cidade");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(180, 80, 60, 16);

        jBGravar.setText("Gravar");
        jBGravar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBGravarActionPerformed(evt);
            }
        });
        getContentPane().add(jBGravar);
        jBGravar.setBounds(190, 250, 80, 40);

        jBSair.setText("Sair");
        jBSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSairActionPerformed(evt);
            }
        });
        getContentPane().add(jBSair);
        jBSair.setBounds(560, 250, 80, 40);

        jTFNumero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFNumeroActionPerformed(evt);
            }
        });
        getContentPane().add(jTFNumero);
        jTFNumero.setBounds(250, 40, 50, 22);

        jLabel6.setText("Número");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(250, 20, 50, 16);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Logradouro", "Número", "Bairro", "Cidade", "Estado", "Cep", "Complemento"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jTable2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jTable2MouseExited(evt);
            }
        });
        jScrollPane2.setViewportView(jTable2);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(10, 300, 668, 250);

        jBAlterar.setText("Alterar");
        jBAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAlterarActionPerformed(evt);
            }
        });
        getContentPane().add(jBAlterar);
        jBAlterar.setBounds(280, 250, 80, 40);

        jBDeletar.setText("Deletar");
        jBDeletar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBDeletarActionPerformed(evt);
            }
        });
        getContentPane().add(jBDeletar);
        jBDeletar.setBounds(370, 250, 80, 40);

        jLabel7.setText("ID");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(330, 20, 20, 16);

        jTFId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFIdActionPerformed(evt);
            }
        });
        getContentPane().add(jTFId);
        jTFId.setBounds(330, 40, 20, 22);

        jBLimpar.setText("Limpar");
        jBLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBLimparActionPerformed(evt);
            }
        });
        getContentPane().add(jBLimpar);
        jBLimpar.setBounds(460, 250, 80, 40);

        jBPesquisar.setText("Pesquisar");
        jBPesquisar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jBPesquisar.setIconTextGap(0);
        jBPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBPesquisarActionPerformed(evt);
            }
        });
        getContentPane().add(jBPesquisar);
        jBPesquisar.setBounds(570, 20, 95, 40);
        getContentPane().add(jTFPesquisar);
        jTFPesquisar.setBounds(410, 30, 140, 22);

        jLabel8.setText("Pesquisar");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(410, 10, 130, 16);
        getContentPane().add(jTFComplemento);
        jTFComplemento.setBounds(170, 160, 130, 22);

        jLabel9.setText("Complemento");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(170, 140, 90, 16);

        jBSelecionar.setText("Selecionar");
        jBSelecionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSelecionarActionPerformed(evt);
            }
        });
        getContentPane().add(jBSelecionar);
        jBSelecionar.setBounds(80, 250, 95, 40);

        try {
            jTFCep.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        getContentPane().add(jTFCep);
        jTFCep.setBounds(30, 160, 130, 22);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTFLogradouroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFLogradouroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFLogradouroActionPerformed

    private void jBGravarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBGravarActionPerformed

        String logradouro = jTFLogradouro.getText().trim();
        String cep = jTFCep.getText().replaceAll("-", "").trim();
        String bairro = jTFBairro.getText().trim();
        String cidade = jTFCidade.getText().trim();
        String estado = jTFEstado.getText().trim();
        String numero = jTFNumero.getText().trim();
        String complemento = jTFComplemento.getText().trim();
        if ("".equals(logradouro) || "".equals(cep) || "".equals(bairro) || "".equals(cidade)
            || "".equals(estado) || "".equals(numero) || "".equals(complemento)) {
            JOptionPane.showMessageDialog(null, "E necessário preencher todos os campos para continuar");
        } else {
            Enderecos endereco = new Enderecos();
            endereco.setBairro(bairro);
            endereco.setCep(cep);
            endereco.setCidade(cidade);
            endereco.setComplemento(complemento);
            endereco.setEstado(estado);
            endereco.setLogradouro(logradouro);
            endereco.setNumero(Integer.parseInt(numero));
            EnderecosDao dao = new EnderecosDao();
            dao.inserir(endereco);
            preencherTabela();
        }
    }//GEN-LAST:event_jBGravarActionPerformed

    private void jBSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBSairActionPerformed
        dispose();
    }//GEN-LAST:event_jBSairActionPerformed

    private void jTFNumeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFNumeroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFNumeroActionPerformed

    private void jTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseClicked
        jTFId.setText(jTable2.getValueAt(jTable2.getSelectedRow(), 0).toString());
        jTFLogradouro.setText(jTable2.getValueAt(jTable2.getSelectedRow(), 1).toString());
        jTFNumero.setText(jTable2.getValueAt(jTable2.getSelectedRow(), 2).toString());
        jTFBairro.setText(jTable2.getValueAt(jTable2.getSelectedRow(), 3).toString());
        jTFCidade.setText(jTable2.getValueAt(jTable2.getSelectedRow(), 4).toString());
        jTFEstado.setText(jTable2.getValueAt(jTable2.getSelectedRow(), 5).toString());
        jTFCep.setText(jTable2.getValueAt(jTable2.getSelectedRow(), 6).toString());
        jTFComplemento.setText(jTable2.getValueAt(jTable2.getSelectedRow(), 7).toString());
        jBAlterar.setEnabled(true);
        jBDeletar.setEnabled(true);
        jBSelecionar.setEnabled(true);
    }//GEN-LAST:event_jTable2MouseClicked

    private void jTable2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jTable2MouseEntered

    private void jTable2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jTable2MouseExited

    private void jBAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAlterarActionPerformed
        int Id = Integer.parseInt(jTFId.getText().trim());
        String logradouro = jTFLogradouro.getText().trim();
        String cep = jTFCep.getText().replaceAll("-", "").trim();
        String bairro = jTFBairro.getText().trim();
        String cidade = jTFCidade.getText().trim();
        String estado = jTFEstado.getText().trim();
        String numero = jTFNumero.getText().trim();
        String complemento = jTFComplemento.getText().trim();
        if ("".equals(logradouro) || "".equals(cep) || "".equals(bairro) || "".equals(cidade)
            || "".equals(estado) || "".equals(numero) || "".equals(complemento)) {
            JOptionPane.showMessageDialog(null, "E necessário preencher todos os campos para continuar");
        } else {
            Enderecos endereco = new Enderecos();
            endereco.setBairro(bairro);
            endereco.setCep(cep);
            endereco.setCidade(cidade);
            endereco.setComplemento(complemento);
            endereco.setEstado(estado);
            endereco.setLogradouro(logradouro);
            endereco.setNumero(Integer.parseInt(numero));
            endereco.setId(Id);
            EnderecosDao dao = new EnderecosDao();
            dao.alterar(endereco);
            preencherTabela();
        }
    }//GEN-LAST:event_jBAlterarActionPerformed

    private void jBDeletarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBDeletarActionPerformed
        int id = Integer.parseInt(jTFId.getText().trim());

        Enderecos endereco = new Enderecos();
        endereco.setId(id);
        EnderecosDao dao = new EnderecosDao();
        dao.deletar(endereco);
        preencherTabela();
    }//GEN-LAST:event_jBDeletarActionPerformed

    private void jTFIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFIdActionPerformed

    }//GEN-LAST:event_jTFIdActionPerformed

    private void jBLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBLimparActionPerformed
        jTFId.setText("");
        jTFLogradouro.setText("");
        jTFCep.setText("");
        jTFEstado.setText("");
        jTFBairro.setText("");
        jTFNumero.setText("");
        jTFCidade.setText("");
        jTFComplemento.setText("");
        jTFPesquisar.setText("");
        preencherTabela();
        jBAlterar.setEnabled(false);
        jBDeletar.setEnabled(false);
        jBSelecionar.setEnabled(false);
    }//GEN-LAST:event_jBLimparActionPerformed

    private void jBPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBPesquisarActionPerformed
        preencherTabelaPesquisar(jTFPesquisar.getText());
    }//GEN-LAST:event_jBPesquisarActionPerformed

    private void jBSelecionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBSelecionarActionPerformed
        valorId = Integer.parseInt(jTFId.getText());
        dispose();
    }//GEN-LAST:event_jBSelecionarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EnderecosTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EnderecosTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EnderecosTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EnderecosTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                EnderecosTela dialog = new EnderecosTela(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBAlterar;
    private javax.swing.JButton jBDeletar;
    private javax.swing.JButton jBGravar;
    private javax.swing.JButton jBLimpar;
    private javax.swing.JButton jBPesquisar;
    private javax.swing.JButton jBSair;
    private javax.swing.JButton jBSelecionar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTFBairro;
    private javax.swing.JFormattedTextField jTFCep;
    private javax.swing.JTextField jTFCidade;
    private javax.swing.JTextField jTFComplemento;
    private javax.swing.JTextField jTFEstado;
    private javax.swing.JTextField jTFId;
    private javax.swing.JTextField jTFLogradouro;
    private javax.swing.JTextField jTFNumero;
    private javax.swing.JTextField jTFPesquisar;
    private javax.swing.JTable jTable2;
    // End of variables declaration//GEN-END:variables

}
