/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Controller.FabricaConexao;
import Model.JFrameComImagem;
import Model.Usuarios;
import java.awt.Image;
import java.awt.Toolkit;
import java.io.IOException;
import java.net.URL;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author LABORATÓRIO
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        setSize(390, 300);// Define resolução tela
        setDefaultCloseOperation(EXIT_ON_CLOSE);// Permite fechar com X
        setLocationRelativeTo(null);//Define a posição como centro da tela
        setTitle("Login");// Titulo da tela
        setResizable(false);//Impede de redimensionar tela
        URL caminhoImagem = this.getClass().getClassLoader().getResource("./images/project/icon-petshop-100.png"); //localiza o icone
        setIconImage(Toolkit.getDefaultToolkit().getImage(caminhoImagem));//define o icone
        imagemFundo(); //Inicializa a imagem de fundo
    }

    //Redimedisiona e localiza define a imagem de imagem de fundo 
    public void imagemFundo() {
        URL caminhoImagem = this.getClass().getClassLoader().getResource("./images/project/meu-petshop-logo.png");
        ImageIcon imagem = new ImageIcon(caminhoImagem);
        Image img = imagem.getImage();
        Image imgScale = img.getScaledInstance(label.getWidth(), label.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon imagemEscalada = new ImageIcon(imgScale);
        label.setIcon(imagemEscalada);
    }

    public void LoginUsuarios(Usuarios us) throws Exception {
        Connection conexao = FabricaConexao.criaConexao();
        PreparedStatement pstmt = null;
        ResultSet rs = null;
        try {
            //String para consultar dados na tabela do Banco que recebe condição para retorno dos dados
            String sql = "select * from usuarios where email =? and senha = ?";
            pstmt = conexao.prepareStatement(sql);
            //recebe as condições estabelecida para consulta
            pstmt.setString(1, us.getLogin());
            pstmt.setString(2, us.getSenha());
            rs = pstmt.executeQuery();
            //verifica o perfil do usuario
            if (rs.next()) {
                String perfil = rs.getString(4);
                switch (perfil) {
                    case "admin" -> {
                        Principal p = new Principal();
                        p.setVisible(true);
                    }
                    case "p1" -> {
                        Principal p = new Principal();
                        p.funcionario();
                        p.setVisible(true);
                    }
                    default ->
                        JOptionPane.showMessageDialog(null, "Nenhum perfil foi atribuido ao usuário, favor contatar o administrador");
                }
                this.dispose();
            } else {
                JOptionPane.showMessageDialog(null, "Dados incorretos");
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jBLogar = new javax.swing.JButton();
        jTFUsuario = new javax.swing.JTextField();
        jPFSenha = new javax.swing.JPasswordField();
        label = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setText("Usuario");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(80, 40, 230, 16);

        jLabel2.setText("Senha");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(80, 100, 220, 16);

        jBLogar.setText("Logar");
        jBLogar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBLogarActionPerformed(evt);
            }
        });
        getContentPane().add(jBLogar);
        jBLogar.setBounds(140, 180, 80, 40);

        jTFUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFUsuarioActionPerformed(evt);
            }
        });
        getContentPane().add(jTFUsuario);
        jTFUsuario.setBounds(80, 60, 230, 22);
        getContentPane().add(jPFSenha);
        jPFSenha.setBounds(80, 120, 230, 22);

        label.setText("jLabel4");
        getContentPane().add(label);
        label.setBounds(0, -40, 370, 370);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //retorna os dados digitados e realiza o Login
    private void jBLogarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBLogarActionPerformed
        String login = jTFUsuario.getText().trim();
        String senha = jPFSenha.getText().trim();

        Usuarios u = new Usuarios();
        u.setLogin(login);
        u.setSenha(senha);

        try {
            this.LoginUsuarios(u);
        } catch (Exception ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jBLogarActionPerformed

    private void jTFUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFUsuarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBLogar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPasswordField jPFSenha;
    private javax.swing.JTextField jTFUsuario;
    private javax.swing.JLabel label;
    // End of variables declaration//GEN-END:variables
}
